// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project


#include "ui.h"
#include "ui_helpers.h"
#include "freertos_task.h"
#include "bluetooth.h"
#include "audioplay.h"
#include "st7789_driver.h"


///////////////////// VARIABLES ////////////////////
uint8_t display_num = 0;
lv_obj_t *main_screen;
lv_obj_t *top_bar;

lv_obj_t *main_menu;
lv_obj_t *settings;
lv_obj_t *play;
lv_obj_t *list;

lv_obj_t *title;

lv_group_t *group;

lv_timer_t *bar_state_update_timer;

lv_obj_t *bluetooth_indicator;

gptimer_handle_t lcd_off_timer = NULL;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
static void Bar_State_Update_Callback(lv_timer_t *timer)
{
    if (Get_A2DP_Global_State() == APP_AV_STATE_CONNECTED)
    {
        lv_obj_clear_flag(bluetooth_indicator, LV_OBJ_FLAG_HIDDEN);
    }
    else
    {
        lv_obj_add_flag(bluetooth_indicator, LV_OBJ_FLAG_HIDDEN);
    }
}

static bool IRAM_ATTR lcd_off_timer_cb(gptimer_handle_t timer, const gptimer_alarm_event_data_t *edata, void *user_data)
{
    st7789_lcd_backlight_set(false);
    gptimer_set_raw_count(lcd_off_timer, 0);
    gptimer_stop(lcd_off_timer);
    return false;
}

void lcd_off_timer_start(void)
{
    gptimer_start(lcd_off_timer);
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    main_screen = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(main_screen, lv_color_hex(0x21312e), 0);
    lv_obj_set_style_border_color(main_screen, lv_color_hex(0x21312e), 0);
    lv_obj_clear_flag(main_screen, LV_OBJ_FLAG_SCROLLABLE);
    top_bar = lv_obj_create(main_screen);
    lv_obj_set_size(top_bar, 300, 40);
    lv_obj_set_pos(top_bar, -5, -5);
    lv_obj_set_style_bg_color(top_bar, lv_color_hex(0x21312e), 0);
    lv_obj_set_style_border_color(top_bar, lv_color_hex(0x21312e), 0);
    lv_obj_set_style_radius(top_bar, 0, 0);
    bluetooth_indicator = lv_img_create(top_bar);
    lv_img_set_src(bluetooth_indicator, LV_SYMBOL_BLUETOOTH);
    lv_obj_set_style_img_recolor_opa(bluetooth_indicator, 255, 0);
    lv_obj_set_style_img_recolor(bluetooth_indicator, lv_color_make(255, 255, 255), 0);
    lv_obj_set_pos(bluetooth_indicator, 10, 5);
    title = lv_label_create(main_screen);
    lv_obj_set_width(title, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(title, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_style_text_font(title, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(title, "HiFi Player");
    lv_obj_set_style_text_color(title, lv_color_make(255, 255, 255), 0);
    lv_obj_set_y(title, 40);
    lv_obj_set_x(title, 85);
    lv_disp_load_scr(main_screen);
    bar_state_update_timer = lv_timer_create(Bar_State_Update_Callback, 500, NULL);
    gptimer_config_t timer_config = {
            .clk_src = GPTIMER_CLK_SRC_DEFAULT,
            .direction = GPTIMER_COUNT_UP,
            .resolution_hz = 1000000, // 1MHz, 1 tick=1us
    };
    ESP_ERROR_CHECK(gptimer_new_timer(&timer_config, &lcd_off_timer));

    gptimer_event_callbacks_t cbs = {
            .on_alarm = lcd_off_timer_cb,
    };
    ESP_ERROR_CHECK(gptimer_register_event_callbacks(lcd_off_timer, &cbs, NULL));
    ESP_ERROR_CHECK(gptimer_enable(lcd_off_timer));
    gptimer_alarm_config_t alarm_config1 = {
            .alarm_count = 5000000, // period = 5s
    };
    ESP_ERROR_CHECK(gptimer_set_alarm_action(lcd_off_timer, &alarm_config1));
    lcd_off_timer_start();
}

void Lv_Widgets_Del_All(lv_obj_t *p)
{
    xQueueOverwrite(lv_widgets_delete_queue, &p);
}
