// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include <driver/gptimer.h>

LV_FONT_DECLARE( lv_font_cn_14 );

extern void Lv_Widgets_Del_All(lv_obj_t* p);
extern void Main_Menu_Init(void);
extern void Menu_Load(void);
extern void Settings_Menu_Init(void);
extern void Settings_Menu_Load(void);
extern void Play_Menu_Init(void);
extern void Play_Menu_Load(void);
extern void Ui_Update_Music_Infos(int32_t f_idx);
extern void List_Menu_Init(void);
extern void List_Menu_Load(void);
extern void List_Add_Music(void);
extern void Bluetooth_Search_Cplt_Callback(void);
extern void Bluetooth_Connected_Callback(void);
extern void lcd_off_timer_start(void);
extern uint8_t display_num;
extern lv_obj_t *main_screen;
extern lv_obj_t *top_bar;
extern lv_obj_t *title;
extern lv_group_t *group;
extern lv_obj_t *main_menu;
extern lv_obj_t *settings;
extern lv_obj_t *play;
extern lv_obj_t *list;
extern gptimer_handle_t lcd_off_timer;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
