// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include <stdio.h>
#include <esp_gap_bt_api.h>
#include "../ui.h"
#include "freertos_task.h"
#include "audioplay.h"
#include "bluetooth.h"

//static lv_obj_t * ui_Label1;
static lv_obj_t *music;
static lv_obj_t *setting;
static lv_obj_t *info_btn;
//
//static lv_obj_t *front;
//
//lv_obj_t* label1;
//lv_obj_t* label2;
//lv_obj_t* label3;

static lv_obj_t *welcome_img;

//LV_IMG_DECLARE(welcome_screen);


lv_anim_t anim;

void Music_Btn_Event_Callback(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED)
    {
        Play_Menu_Init();
        List_Menu_Init();
        lv_obj_add_flag(main_menu, LV_OBJ_FLAG_HIDDEN);
        lv_group_remove_all_objs(group);
        Play_Menu_Load();
        xSemaphoreGive(audio_task_create_semphore);
    }
}

void Setting_Btn_Event_Callback(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED)
    {
        bluetooth_app_main();
        Settings_Menu_Init();
        lv_obj_add_flag(main_menu, LV_OBJ_FLAG_HIDDEN);
        lv_group_remove_all_objs(group);
        Settings_Menu_Load();
//        esp_bt_gap_start_discovery(ESP_BT_INQ_MODE_GENERAL_INQUIRY, 5, 0);
        printf("设置按钮按下\n");
    }
}

void Info_Btn_Event_Callback(lv_event_t *e)
{
    lv_group_remove_all_objs(group);
    lv_obj_add_flag(main_menu, LV_OBJ_FLAG_HIDDEN);
    Info_Menu_Load();
}

void Menu_Load(void)
{
    lv_obj_clear_flag(main_menu, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(title, "HiFi Player");
    lv_group_add_obj(group, music);
    lv_group_add_obj(group, setting);
    lv_group_add_obj(group, info_btn);
    display_num = 0;
}

void Main_Menu_Init(void)
{
    extern lv_indev_t *indev_keypad;
    static lv_obj_t *music_btn_icon;
    static lv_obj_t *setting_btn_icon;
    static lv_obj_t *info_btn_icon;

    group = lv_group_create();
    lv_group_set_editing(group, false);
    lv_indev_set_group(indev_keypad, group);

//    lv_anim_init(&anim);
    main_menu = lv_obj_create(main_screen);
//    lv_anim_set_var(&anim, main_menu);
//    lv_anim_set_exec_cb(&anim, (lv_anim_exec_xcb_t)lv_obj_set_y);
//    lv_anim_set_values(&anim, 240, 75);
//    lv_anim_set_path_cb(&anim, lv_anim_path_ease_out);
//    lv_anim_set_time(&anim, 500);

    lv_obj_set_size(main_menu, 280, 175);
    lv_obj_clear_flag(main_menu, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_pos(main_menu, 0, 75);
    lv_obj_set_style_radius(main_menu, 45, 0);
    lv_obj_set_style_shadow_color(main_menu, lv_color_make(0, 0, 0), 0);
    lv_obj_set_style_shadow_width(main_menu, 20, 0);
    lv_obj_set_style_shadow_ofs_y(main_menu, -10, 0);

//    ui_Label1 = lv_label_create(main_menu);
//    lv_obj_set_style_text_font(ui_Label1, &lv_font_simsun_16_cjk, LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 3
//    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 3
//    lv_obj_set_x(ui_Label1, 0);
//    lv_obj_set_y(ui_Label1, 0);
//    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
//    lv_label_set_text(ui_Label1, "你好 こんにちは hello");
    music = lv_btn_create(main_screen);
    setting = lv_btn_create(main_screen);
    info_btn = lv_btn_create(main_screen);
    lv_obj_add_event_cb(setting, Setting_Btn_Event_Callback, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(music, Music_Btn_Event_Callback, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(info_btn, Info_Btn_Event_Callback, LV_EVENT_CLICKED, NULL);
    lv_obj_set_size(music, 70, 70);
    lv_obj_set_pos(music, 105 - 15, 95 - 75);
    lv_obj_set_style_radius(music, 40, 0);
    lv_obj_set_style_bg_color(music, lv_color_hex(0x33d0b3), 0);
    lv_obj_set_size(setting, 50, 50);
    lv_obj_set_pos(setting, 28 - 15, 154 - 75);
    lv_obj_set_style_radius(setting, 40, 0);
    lv_obj_set_style_bg_color(setting, lv_color_hex(0xeeb54e), 0);
    lv_obj_set_size(info_btn, 50, 50);
    lv_obj_set_pos(info_btn, 205 - 15, 154 - 75);
    lv_obj_set_style_radius(info_btn, 40, 0);
    lv_obj_set_style_bg_color(info_btn, lv_color_hex(0xe0e4e3), 0);
    lv_obj_set_parent(music, main_menu);
    lv_obj_set_parent(setting, main_menu);
    lv_obj_set_parent(info_btn, main_menu);

    music_btn_icon = lv_img_create(music);
    setting_btn_icon = lv_img_create(setting);
    info_btn_icon = lv_img_create(info_btn);
    lv_img_set_src(music_btn_icon, LV_SYMBOL_AUDIO);
    lv_img_set_src(setting_btn_icon, LV_SYMBOL_SETTINGS);
    lv_img_set_src(info_btn_icon, LV_SYMBOL_ENVELOPE);
    lv_obj_center(music_btn_icon);
    lv_obj_center(setting_btn_icon);
    lv_obj_center(info_btn_icon);

    lv_group_set_editing(group, false);
    lv_group_add_obj(group, music);
    lv_group_add_obj(group, setting);
    lv_group_add_obj(group, info_btn);
//    lv_anim_start(&anim);
}

//void ui_Screen1_screen_init(void)
//{
//    extern lv_indev_t *indev_keypad;
//    static lv_group_t *group;
//    static lv_style_t front_style;
//    group = lv_group_create();
//    lv_indev_set_group(indev_keypad, group);	//将组绑定到输入设备
//    ui_Screen1 = lv_obj_create(NULL);
//    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//
//    welcome_img = lv_img_create(ui_Screen1);
//    lv_img_set_src(welcome_img, "/sdcard/PIC/welcome.png");
//    lv_obj_set_align(welcome_img, LV_ALIGN_CENTER);
//
//    front = lv_obj_create(ui_Screen1);
//    lv_obj_set_size(front, 260, 220);
//    lv_obj_set_align(front, LV_ALIGN_CENTER);
//
//    lv_style_init(&front_style);
//    lv_style_set_radius(&front_style, 45);
//    lv_style_set_bg_color(&front_style, lv_color_make(255, 255, 255)); /* 设置背景颜色 */
//    lv_style_set_opa(&front_style, LV_OPA_70);
//    lv_obj_add_style(front, &front_style, LV_PART_MAIN | LV_STATE_DEFAULT);
//
////    ui_Label1 = lv_label_create(ui_Screen1);
////    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 3
////    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 3
////    lv_obj_set_x(ui_Label1, 0);
////    lv_obj_set_y(ui_Label1, 0);
////    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
////    lv_label_set_text(ui_Label1, "Misaka's LVGL Demo");
////    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
////
////    butten1 = lv_btn_create(front);
////    lv_obj_set_width(butten1, LV_SIZE_CONTENT);   /// 3
////    lv_obj_set_height(butten1, LV_SIZE_CONTENT);    /// 3
////    lv_obj_center(butten1);
////    label1 = lv_label_create(butten1);
////    lv_obj_set_style_text_font(label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
////    lv_label_set_text(label1, "Btn 1"); /* 设置标签文本 */
////    lv_obj_set_align(label1,LV_ALIGN_CENTER); /* 设置标签位置 */
////
////    butten2 = lv_btn_create(ui_Screen1);
////    lv_obj_set_width(butten2, LV_SIZE_CONTENT);   /// 3
////    lv_obj_set_height(butten2, LV_SIZE_CONTENT);    /// 3
////    lv_obj_set_x(butten2, 150);
////    lv_obj_set_y(butten2, 20);
////    label2 = lv_label_create(butten2);
////    lv_obj_set_style_text_font(label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
////    lv_label_set_text(label2, "Btn 2"); /* 设置标签文本 */
////    lv_obj_set_align(label2,LV_ALIGN_CENTER); /* 设置标签位置 */
////
////    butten3 = lv_btn_create(ui_Screen1);
////    lv_obj_set_width(butten3, LV_SIZE_CONTENT);   /// 3
////    lv_obj_set_height(butten3, LV_SIZE_CONTENT);    /// 3
////    lv_obj_set_x(butten3, 20);
////    lv_obj_set_y(butten3, 150);
////    label3 = lv_label_create(butten3);
////    lv_obj_set_style_text_font(label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
////    lv_label_set_text(label3, "Btn 3"); /* 设置标签文本 */
////    lv_obj_set_align(label3,LV_ALIGN_CENTER); /* 设置标签位置 */
////
////    lv_group_set_editing(group, false);   //导航模式
////    lv_group_add_obj(group, butten1);
////    lv_group_add_obj(group, butten2);
////    lv_group_add_obj(group, butten3);
//}
